### ISSUE TITLE
[FRONTEND] Fix editorial page

### ISSUE THREAD

**Issue by w1lldone** [bppugm/ugm-proceeding#284]
https://digitalpress.ugm.ac.id/editorial
For each person, add links for:
- Scopus
- Email

**Comment by w1lldone** [comment]
# Pak Widodo

**Comment by w1lldone** [comment]
## Bu Mutiah
- [ ] Email: mutiah.a@ugm.ac.id
- [ ] Acadstaff: https://acadstaff.ugm.ac.id/MTk3MDA2MDUyMDAwMDMyMDAx

**Comment by w1lldone** [comment]
## Bu Nuning
- [ ] Email: tririni@ugm.ac.id
- [ ] Scopus: https://www.scopus.com/authid/detail.uri?authorId=55184030800
- [ ] Acadstaff: https://acadstaff.ugm.ac.id/nuning

**Comment by w1lldone** [comment]
## Pak Wayan
- [ ] Acadstaff: https://acadstaff.ugm.ac.id/OTkwMDAwMjIy
- [ ] Email: wmustika@ugm.ac.id
- [ ] Scopus: https://www.scopus.com/authid/detail.uri?authorId=36185944100
- [ ] OrcID: https://orcid.org/0000-0002-0207-261X

**Comment by w1lldone** [comment]
## Rafieiy 
@davieiycode You can complete this on your own :laughing: 
- [ ] Linkedin: https://www.linkedin.com/in/rafieiy/

**Comment by w1lldone** [comment]
## Pak Syahrul
- [ ] Linkedin: https://www.linkedin.com/in/syahrul-fauzi-740205b3/

**Comment by hardybs94** [comment]
ORCID: https://orcid.org/0000-0001-5170-7389
GitHub: https://github.com/hardybs94
