### ISSUE TITLE
[FRONT PAGE] Introductory Caption

### ISSUE THREAD

**Issue by dyligently** [bppugm/ugm-proceeding#409]
## Update caption in https://digitalpress.ugm.ac.id/ :

![image](https://user-images.githubusercontent.com/19965509/61345810-c8d20c80-a880-11e9-9c9f-964f2c1830ff.png)

### From
>UGM Digital press, managed by Badan Penerbit dan Publikasi UGM, provides open access scientific conference proceedings. The collection of scientific papers from the international conference published in 4 major series: Physical Sciences & Engineering, Life Sciences, Health Sciences, and Social Sciences & Humanities.

### to

>As an open-source platform for a series of potentially cutting-edge proceeding papers, the UGM Digital Press is dedicated to build public trust through strong publication ethics and societal commitment to provide an authentic and intellectually stimulating articles.

### From
> UGM Digital Press is a publishing platform for international conference papers and UGM Press published scientific books. All manuscript published at UGM Digital Press are selected strictly through a review process to preserve the quality of published scientific works.
>
>The collection of scientific papers from the international conference can be found in the UGM Digital Press Proceeding Series which are sourced from the Universitas Gadjah Mada Annual Scientific Conferences (UASC), such as ICST, ICHS, ICTA, ICSEAS, BioMIC, and other international conferences held by UGM.
>
>The scientific works of international conference published at UGM Digital Press will get a DOI and be indexed in Google Scholars. This platform is designed to be easily accessible anywhere and open access. All documents published at the UGM Digital Press are licensed by Creative Commons Attribution License (CC-BY). UGM Digital Press development continues to be pursued by working together and associating with reputable indexing institutions such as Crossref and Dimension.
>
>UGM Digital Press is managed directly by the Badan Penerbit dan Publikasi Universitas Gadjah Mada and is supported by Direktorat Sistem dan Sumber Daya Informasi Universitas Gadjah Mada.
### To

> As an open-source platform for a series of potentially cutting-edge proceeding papers, the UGM Digital Press is dedicated to build public trust through strong publication ethics and societal commitment to provide an authentic and intellectually stimulating articles. It publishes international conference papers and UGM Press scientific books. All manuscript published on the UGM Digital Press are strictly assessed through a review process and thus, it ensures the quality of the selected articles.
> 
> The collection of scientific papers from the international conference can be accessed on the UGM Digital Press Proceeding Series. They are part of the Universitas Gadjah Mada Annual Scientific Conferences (UASC). Its agenda comprises ICST, ICHS, ICTA, ICSEAS, BioMIC, and other international conferences independently organized by faculties or working units within the compound of Universitas Gadjah Mada.
> 
> The scientific works of international conference published on the UGM Digital Press will be assigned DOIs and indexed on Google Scholars. All documents published are licensed by Creative Commons Attribution License (CC-BY). To progress further, the UGM Digital Press continues to collaborate with reputable indexing institutions such as Crossref and Dimension and the like.

Note: Create a branch directly from `master`

**Comment by w1lldone** [comment]
Nice 👍 i will get right into it soon

**Comment by w1lldone** [comment]
So, do you agree with:
### Discover Our Conference Proceedings Collections
sentence?

**Comment by dyligently** [comment]
Yes! Enough as an introductory title to reflect all 4 proceeding series!

**Comment by w1lldone** [comment]
i Like this one better:

> 
> As an open-source platform for a series of potentially cutting-edge proceeding papers, the UGM Digital Press is dedicated to build public trust through strong publication ethics and societal commitment to provide an authentic and intellectually stimulating articles.

**Comment by dyligently** [comment]
I'd say put them both! If not, I made them flexible enough to be put somewhere in the website! (y)

**Comment by dyligently** [comment]
I'd say put them both! If not, I made them flexible enough to be put somewhere in the website!

**Comment by w1lldone** [comment]
We can put one of them in the about page. Check this out https://digitalpress.ugm.ac.id/about

**Comment by w1lldone** [comment]
We can put this in the about page

> To sustain academic prolificacy through publications, Badan Penerbit dan Publikasi (BPP UGM) proudly presents the UGM Digital Press. There are 4 series to represent the core purpose of Gadjah Mada largest interdisciplinary collaboration, making it the most diverse in terms of scientific community in Indonesia.

**Comment by w1lldone** [comment]
i think it serves the purpose of an about page

**Comment by dyligently** [comment]
Exactly! It can go like this:

As an open-source platform for a series of potentially cutting-edge proceeding papers, the UGM Digital Press is dedicated to build public trust through strong publication ethics and societal commitment to provide an authentic and intellectually stimulating articles. It publishes international conference papers and UGM Press scientific books. All manuscript published on the UGM Digital Press are strictly assessed through a review process and thus, it ensures the quality of the selected articles.

The collection of scientific papers from the international conference can be accessed on the UGM Digital Press Proceeding Series. They are part of the Universitas Gadjah Mada Annual Scientific Conferences (UASC). Its agenda comprises ICST, ICHS, ICTA, ICSEAS, BioMIC, and other international conferences independently organized by faculties or working units within the compound of Universitas Gadjah Mada.

The scientific works of international conference published on the UGM Digital Press will be assigned DOIs and indexed on Google Scholars. All documents published are licensed by Creative Commons Attribution License (CC-BY). To progress further, the UGM Digital Press continues to collaborate with reputable indexing institutions such as Crossref and Dimension and the like.

**Comment by w1lldone** [comment]
> Exactly! It can go like this:
> 
> As an open-source platform for a series of potentially cutting-edge proceeding papers, the UGM Digital Press is dedicated to build public trust through strong publication ethics and societal commitment to provide an authentic and intellectually stimulating articles. It publishes international conference papers and UGM Press scientific books. All manuscript published on the UGM Digital Press are strictly assessed through a review process and thus, it ensures the quality of the selected articles.
> 
> The collection of scientific papers from the international conference can be accessed on the UGM Digital Press Proceeding Series. They are part of the Universitas Gadjah Mada Annual Scientific Conferences (UASC). Its agenda comprises ICST, ICHS, ICTA, ICSEAS, BioMIC, and other international conferences independently organized by faculties or working units within the compound of Universitas Gadjah Mada.
> 
> The scientific works of international conference published on the UGM Digital Press will be assigned DOIs and indexed on Google Scholars. All documents published are licensed by Creative Commons Attribution License (CC-BY). To progress further, the UGM Digital Press continues to collaborate with reputable indexing institutions such as Crossref and Dimension and the like.

Much better from the previous one

**Comment by dyligently** [comment]
> > Exactly! It can go like this:
> > As an open-source platform for a series of potentially cutting-edge proceeding papers, the UGM Digital Press is dedicated to build public trust through strong publication ethics and societal commitment to provide an authentic and intellectually stimulating articles. It publishes international conference papers and UGM Press scientific books. All manuscript published on the UGM Digital Press are strictly assessed through a review process and thus, it ensures the quality of the selected articles.
> > The collection of scientific papers from the international conference can be accessed on the UGM Digital Press Proceeding Series. They are part of the Universitas Gadjah Mada Annual Scientific Conferences (UASC). Its agenda comprises ICST, ICHS, ICTA, ICSEAS, BioMIC, and other international conferences independently organized by faculties or working units within the compound of Universitas Gadjah Mada.
> > The scientific works of international conference published on the UGM Digital Press will be assigned DOIs and indexed on Google Scholars. All documents published are licensed by Creative Commons Attribution License (CC-BY). To progress further, the UGM Digital Press continues to collaborate with reputable indexing institutions such as Crossref and Dimension and the like.
> 
> Much better from the previous one

Thanks for the input! @w1lldone

**Comment by w1lldone** [comment]
i will update the description and assign @ulfaintania to this issue.
