### ISSUE TITLE
[CONTENT] Fix Organizer Guidelines

### ISSUE THREAD

**Issue by w1lldone** [bppugm/ugm-proceeding#422]
- Table of contents
- Preparing the files

**Comment by dyligently** [comment]
Done, please refer to this link

https://drive.google.com/open?id=1ltdHz3ZvT6UsfxAxGMtJmZ_ss4UG6-J8NMVPFHOxTkA

And the revised version of the TOC

![toc-revised](https://user-images.githubusercontent.com/47406980/63563856-cbfd9e00-c58c-11e9-8adb-913e4544e23f.jpg)

**Comment by w1lldone** [comment]
Good work :+1:
