### ISSUE TITLE
[CONTENT] Make dedicated template for each series

### ISSUE THREAD

**Issue by w1lldone** [bppugm/ugm-proceeding#423]
- Remove header and footer
- Edit the page number, different first page
- Dedicated template for SSH + APA Reference Style Guidelines
- Dedicated template for the rest + Springer MathPhys Reference Style Guidelines
- Archive the guidelines for each series

**Comment by dyligently** [comment]
Done! Check out these links

HS
https://drive.google.com/open?id=1jvGyLwk8mKyfJd8AI6KXXzWaidFYSs_T

LS
https://drive.google.com/open?id=13usvKCaYU7Td9Hmg6-XXy6ZcBtjwNJs0

PSE
https://drive.google.com/open?id=1O1WJirZ6XFDKsZMSI30GHksOvzaveX5L

SSH
https://drive.google.com/open?id=1o-Ib-RmjaGFFhQMaW9FGFUJwXEwn6-bO

**Comment by w1lldone** [comment]
I have stored all those link to their prespective series. Well done @dyligently :+1:
