### ISSUE TITLE
[CONTENT] Fix Author Guidelines

### ISSUE THREAD

**Issue by w1lldone** [bppugm/ugm-proceeding#424]
Indicate manuscript language should be in English. But it's possible for other UN Official language too (In request)

**Comment by dyligently** [comment]
Jump to this Manuscript Preparation

Manuscript submission must be in English, preferably written using the American spelling (en-us, EN-US). Submission in other languages may be possible for as long as the language is recognized by the United Nations. A further consultation to the UGM Digital Press editorial staff is necessary should there be this type of submission. Please see the list of language on this link https://www.un.org/en/sections/about-un/official-languages/

Other linguistic aspects are considered a higher importance which include matters such as a correct use of grammar, spelling, accurate scientific terms and the like. It will likely result in distraction from the science being discussed in a manuscript and a delay in publication. To prevent this scenario, it is strongly encouraged for the authors to have their manuscripts proofread by native speaker colleagues. An additional fee might be charged should there be a need to extensively correct manuscript by the Editorial Staff at UGM Digital Press.

**Comment by w1lldone** [comment]
Nice :+1:
